version: '3.4'
services:
    gcf-debug:
        build:
            context: ../../
            dockerfile: Container/Dockerfile
            target: debug
            args:
                VARIANT: 3.7

        command: sleep infinity

        volumes:
            - ../../:/workspace:cached
            - C:\_dev\credentials\gcp\dev-user.json:/_dev/credentials/gcp/dev-user.json:cached
            # Store extensions for quicker rebuilding. Just delete the volumes if they need to be cleaned
            - extensions:/root/.vscode-server/extensions
            - insiders-extensions:/root/.vscode-server-insiders/extensions

volumes:
    extensions:
    insiders-extensions: