steps:
- name: gcr.io/$PROJECT_ID/docker-compose
  args:
    - -f
    - .devcontainer/docker-compose.yml
    - -f
    - ../_container/docker-compose.yml
    - -f
    - ../_container/docker-compose.cloud.yml
    - build
  dir: ${_FUNCTION}
  env:
    - PROJECT_ID=$PROJECT_ID
    - FUNCTION=${_FUNCTION}

substitutions:
  _FUNCTION: _template

timeout: 120s

images:
- gcr.io/$PROJECT_ID/gcf-debug-${_FUNCTION}:latest