steps:
- id: format
  name: gcr.io/$PROJECT_ID/gcf-debug-${_FUNCTION}:latest
  args:
    - format
    - --check
  entrypoint: bash
  waitFor: ['-']
  dir: ${_FUNCTION}

- id: flake8
  name: gcr.io/$PROJECT_ID/gcf-debug-${_FUNCTION}:latest
  args:
    - lint_flake8
  entrypoint: bash
  waitFor:
    - format
  dir: ${_FUNCTION}

- id: mypy
  name: gcr.io/$PROJECT_ID/gcf-debug-${_FUNCTION}:latest
  args:
    - lint_mypy
  entrypoint: bash
  waitFor:
    - format
  dir: ${_FUNCTION}

- id: Unit tests
  name: gcr.io/$PROJECT_ID/gcf-debug-${_FUNCTION}:latest
  args:
    - test
    - --ignore=tests/
    - --cov-report=xml
  entrypoint: bash
  waitFor:
    - flake8
    - mypy
    - format
  env:
    - FUNCTION=${_FUNCTION}
  dir: ${_FUNCTION}

- id: Get Secrets
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args: [ '-c', 'gcloud secrets versions access latest --secret=gcf-testing-secrets > .env' ]
  dir: ${_FUNCTION}

- id: Integration tests
  name: gcr.io/$PROJECT_ID/gcf-debug-${_FUNCTION}:latest
  args:
    - test
    - --cov-report=xml
    - --cov-append
    - tests/test_${_FUNCTION}.py
  entrypoint: bash
  env:
    - FUNCTION=${_FUNCTION}
  dir: ${_FUNCTION}

- id: Deploy test
  name: gcr.io/cloud-builders/gcloud
  args:
  - functions
  - deploy
  - ${_FUNCTION}-test
  - --trigger-resource=${_TEST_BUCKET}
  - --trigger-event=google.storage.object.finalize
  - --memory=128MB
  - --max-instances=1
  - --region=europe-west1
  - --entry-point=${_FUNCTION}
  - --runtime=${_PYTHON_RUNTIME}
  dir: ${_FUNCTION}

- id: Event tests
  name: gcr.io/$PROJECT_ID/gcf-debug-${_FUNCTION}:latest
  args:
    - test
    - --no-cov
    - tests/test_events.py
  entrypoint: bash
  env:
    - FUNCTION=${_FUNCTION}
  dir: ${_FUNCTION}

- id: Deploy test (Cleanup)
  name: gcr.io/cloud-builders/gcloud
  args:
  - functions
  - delete
  - ${_FUNCTION}-test
  - --region=europe-west1
  dir: ${_FUNCTION}

timeout: 180s

substitutions:
  _FUNCTION: _template
  _PYTHON_RUNTIME: python37
  _TEST_BUCKET: eta-testing-bucket